# MediaWiki with MariaDB
#
version: "2"
services:
  mediawiki:
    image: docker.io/dyliss/wiki-metabolic-network-img
    restart: always
    ports:
      - 80:80
    links:
      - database
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wikidb
      MYSQL_USER: wikidb_user
      MYSQL_PASSWORD: wikidb_pwd
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
